[ci] add gradle wrapper validation action
wpilibsuite/vendor-template pull request #31
Opened 2024-02-20 05:52 UTC by spacey-sooty

2024-09-18 19:31 UTC, calcmogul requested changes

2024-09-18 19:31 UTC, calcmogul commented on .github/workflows/gradle-wrapper-validation.yml
> +      - uses: gradle/wrapper-validation-action@v2
This PR has been sitting so long, the latest version of this action is now v3.

2025-06-24 03:01 UTC, sciencewhiz commented on .github/workflows/gradle-wrapper-validation.yml
> +      - uses: gradle/wrapper-validation-action@v2
Now its `gradle/actions/wrapper-validation@v4`

2025-11-20 15:35 UTC, sciencewhiz commented
It also needs to be changed to 2026 branch

2025-11-26 16:27 UTC, spacey-sooty commented
Superceded by #61

2025-11-26 16:27 UTC, closed without merging